# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: ".xyz"
subtitle: "dimspace"
#logo: "assets/light-bulb.png"
icon: "fas fa-lightbulb"

header: true
footer: false

# footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>'  # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional message

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "github"
    icon: "fab fa-github"
    url: "https://github.com"
    target: '_blank' 
  - name: "reddit"
    icon: "fab fa-reddit"
    url: "https://reddit.com"
    target: '_blank' 
  - name: "wikipedia"
    icon: "fab fa-wikipedia-w"
    url: "https://wikipedia.com"
    target: '_blank' 
  - name: "theguardian"
    icon: "fas fa-newspaper"
    url: "https://www.theguardian.com/uk"
    target: '_blank' 
  - name: "qwant"
    icon: "fab fa-searchengin"
    url: "https://qwant.com"
    target: '_blank' 
  - name: "yougov"
    icon: "fas fa-poll-h"
    url: "https://yougov.co.uk"
    target: '_blank' 

services:
  - name: "Home Server"
    icon: "fas fa-server"
    items:
      - name: "Nextcloud"
        logo: "assets/tools/nextcloud.png"
        subtitle: "my personal nextcloud server"
        tag: "cloud"
        tagstyle: "is-success"
        url: "https://cloud.dimspace.xyz/"
        target: '_blank' 
      - name: "Webmin"
        logo: "assets/tools/webmin.png"
        subtitle: "server manager panel"
        url: "http://192.168.1.248:10000/"
        target: '_blank' 
        tagstyle: "is-warning"
        tag: "admin"
      - name: "Privatebin"
        logo: "assets/tools/privatebin.png"
        subtitle: "secure self-hosted pastebin"
        tag: "text"
        tagstyle: "is-success"
        url: "https://bin.dimspace.xyz"
        target: '_blank' 
      - name: "Shlink"
        logo: "assets/tools/shlink.png"
        subtitle: "personal self hosted link shortener"
        tag: "shorten"
        tagstyle: "is-success"
        url: "https://app.dimspace.xyz"
        target: '_blank'
      - name: "PHPmyadmin"
        logo: "assets/tools/phpmyadmin.png"
        subtitle: "database management"
        tag: "database"
        tagstyle: "is-warning"
        url: "https://pma.dimspace.xyz"
        target: '_blank' 
      - name: "Wordpress"
        logo: "assets/tools/wordpress.png"
        #icon: "fab fa-wordpress"
        subtitle: "my self-hosted wordpress"
        tag: "blog"
        tagstyle: "is-success"
        url: "https://blog.dimspace.xyz"
        target: '_blank'
      - name: "AirSonic"
        logo: "assets/tools/airsonic.png"
        #icon: "fab fa-wordpress"
        subtitle: "my self-hosted media server"
        tag: "music"
        tagstyle: "is-success"
        url: "https://airsonic.dimspace.xyz"
        target: '_blank'
      - name: "Passbolt"
        logo: "assets/tools/passbolt.png"
        subtitle: "secure password manager"
        tag: "passwords"
        tagstyle: "is-danger"
        url: "https://pass.dimspace.xyz/"
        target: '_blank'
      - name: "Tiny Tiny RSS"
        logo: "assets/tools/ttrss2.png"
        subtitle: "OFFLINE"
        tag: "news"
        tagstyle: "is-danger"
        url: #
        target: '_blank'
      - name: "Bookstack"
        logo: "assets/tools/bookstack.png"
        subtitle: "OFFLINE"
        tag: "books"
        tagstyle: "is-danger"
        url: #
        target: '_blank'
      - name: "Wallabag"
        logo: "assets/tools/wallabag.png"
        subtitle: "save webpages to read later"
        tag: "pocket"
        tagstyle: "is-danger"
        url: "#"
        target: '_blank' 
      - name: "Shaarli"
        logo: "assets/tools/shaarli.png"
        subtitle: "simple link sharing"
        tag: "links"
        tagstyle: "is-success"
        url: "https://links.dimspace.xyz"
        target: '_blank'
  - name: "Useful Links"
    icon: "fas fa-server"
    items:
      - name: "Mod Security"
        logo: "assets/tools/modsecurity.png"
        subtitle: "how to install on ubuntu"
        tag: "security"
        tagstyle: "is-danger"
        url: "https://www.linuxbabe.com/security/modsecurity-apache-debian-ubuntu"
        target: '_blank'
      - name: "Fail 2 Ban"
        logo: "assets/tools/fail2ban.png"
        subtitle: "how to install on ubuntu"
        tag: "security"
        tagstyle: "is-danger"
        url: "https://ubuntu.tutorials24x7.com/blog/how-to-install-fail2ban-on-ubuntu-20-04-lts"
        target: '_blank'
  - name: "My Writing"
    icon: "fas fa-pen-alt"
    items:
      - name: "Blog"
        logo: "assets/tools/wordpress.png"
        #icon: "fab fa-wordpress"
        subtitle: "my blog"
        tag: "blog"
        url: "https://blog.dimspace.xyz"
        target: '_blank' 
      - name: "Bodylock MMA"
        logo: "assets/tools/tbl.png"
        subtitle: "my work on the bodylock mma"
        tag: "mma"
        url: "https://thebodylockmma.com/author/davemarsdin/"
        target: '_blank' 	
      - name: "Cyclismas"
        #logo: "assets/tools/tbl.png"
        icon: "fas fa-bicycle"
        subtitle: "old cycling ramblings"
        tag: "cycling"
        url: "http://www.cyclismas.com/biscuits/author/dimspace/"
        target: '_blank' 	
  - name: "Social"
    icon: "fas fa-thumbs-up"
    items:
      - name: "Twitter"
        logo: "assets/tools/twitter.png"
        subtitle: "follow me on twitter"
        tag: "tweet"
        url: "https://twitter.com/dimspace"
        target: '_blank' 	
      - name: "Facebook"
        logo: "assets/tools/facebook.png"
        subtitle: "i don't use this much"
        tag: "post"
        url: "https://facebook.com/dimspace"
        target: '_blank' 
      - name: "Instagram"
        logo: "assets/tools/instagram.png"
        subtitle: "i use this even less"
        tag: "post"
        url: "https://instagram.com/dimspace"
        target: '_blank' 
      - name: "youtube"
        logo: "assets/tools/youtube.png"
        subtitle: "um"
        tag: "play"
        url: "#"
        target: '_blank' 
  - name: "Sound & Vision"
    icon: "fas fa-play"
    items:
      - name: "Last.fm"
        logo: "assets/tools/lastfm.png"
        subtitle: "what i listen to"
        tag: "music"
        url: "https://last.fm/user/dimspace"
        target: '_blank' 
      - name: "Trakt.tv"
        logo: "assets/tools/trakt.png"
        subtitle: "what i watch"
        url: "https://trakt.tv/users/dimspace"
        target: '_blank' 
        tag: "tv"
      - name: "Musicbrainz"
        logo: "assets/tools/musicbrainz.png"
        subtitle: "my complete music collection"
        tag: "music"
        url: "https://musicbrainz.org/collection/7a1289c9-2e2a-4c81-80ff-ba14f044357d"
        target: '_blank' 
      - name: "The Audio Database"
        logo: "assets/tools/bars.png"
        subtitle: "my audiodb edits"
        tag: "music"
        url: "https://www.theaudiodb.com/user/dimspace"
        target: '_blank' 
  - name: "Geek Stuff"
    icon: "fas fa-code-branch"
    items:
      - name: "Github"
        logo: "assets/tools/github.png"
        subtitle: "my git"
        tag: "git"
        url: "http://github.com/dm2912"
        target: '_blank' 
      - name: "Userstyles"
        logo: "assets/tools/userstyles.png"
        subtitle: "my custom styles on userstyles"
        url: "https://userstyles.org/users/304746"
        target: '_blank' 
        tag: "css"
      - name: "Wikipedia"
        logo: "assets/tools/wikipedia.png"
        subtitle: "my wiki edits"
        tag: "wiki"
        url: "https://en.wikipedia.org/wiki/User_talk:Dimspace"
        target: '_blank' 
  - name: "Anti doping"
    icon: "fas fa-syringe"
    items:
      - name: "UFC Testing"
        logo: "assets/tools/usada.png"
        subtitle: "ufc/usada test stats spreadsheet"
        tag: "usada"
        url: "https://short.dimspace.xyz/ufcusada"
        target: '_blank' 
      - name: "UFC Test Records"
        logo: "assets/tools/ufc.png"
        subtitle: "various ufc athlete test results"
        url: "https://cloud.dimspace.xyz/s/8inB9xMtRXL7dPd"
        target: '_blank' 
        tag: "css"
      - name: "Operation Puerto"
        logo: "assets/tools/spain.png"
        subtitle: "various Operation Puerto evidence"
        tag: "fuentes"
        url: "hhttps://short.dimspace.xyz/puerto"
        target: '_blank' 
      - name: "Lance Armstrong"
        logo: "assets/tools/texas.png"
        subtitle: "a bunch of Armstrong related stuff"
        tag: "big tex"
        url: "https://short.dimspace.xyz/lance"
        target: '_blank' 
      - name: "Blog"
        logo: "assets/tools/wordpress.png"
        #icon: "fab fa-wordpress"
        subtitle: "my blog"
        tag: "blog"
        url: "https://blog.dimspace.xyz/"
        target: '_blank' 
      - name: "Bodylock MMA"
        logo: "assets/tools/tbl.png"
        subtitle: "my work on the bodylock mma"
        tag: "mma"
        url: "https://thebodylockmma.com/author/davemarsdin/"
        target: '_blank'
